function fixup($file){
  $content = Get-Content $file -Raw

  $content = $content.Replace('/*','')
  $content = $content.Replace(' * This Java source file was generated by the Gradle ''init'' task.','')
  $content = $content.Replace(' */','')

  Set-Content $file $content -NoNewline
}

Get-ChildItem -Recurse App.java,AppTest.java | %{fixup $_}
